layout_spectrum: 0.7491736215019211
typography_spectrum: 0.8908870710406711
color:
  brandStrength: 0.32770731114247575
  lightness: 0.6212983458443997
  saturation: 0.6531304244334708
  rhythmicContrast: 0.05843410304111272
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
github: true
opengraph:
  appId: ''
analytics:
  google: UA-112930135-1
author:
  name: Roberto Esquenazi
  email: robertoesquenazi@gmail.com
name: Roberto Esquenazi
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Social
    url: 'https://linktr.ee/rubbertoe3'
    type: external
  - name: View in Google Drive
    url: 'https://drive.google.com/open?id=10xJm9C3t9reB0B06u7K9pb5eTwnmubSX'
    type: external
  - name: Credits
    id: 50c81b70-2742-4766-ab85-5e47498af8c9
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bd0fb5a-6f1c-4804-966f-dc0a4928fc64.jpg
title: Roberto Esquenazi
content: []
description: My Virtual Portfolio
purpose:
  - type: contact
    url: 'mailto:robertoesquenazi@gmail.com'
    label: Email Me
  - type: external
    url: 'https://api.whatsapp.com/send?phone=50761308800'
    label: Whatsapp
